'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import { FiArrowRight, FiCode, FiDatabase, FiGlobe, FiLayout, FiShield, FiZap } from 'react-icons/fi';

const templates = [
    { icon: FiLayout, title: 'React Dashboard', desc: 'Full dashboard layout with sidebar, charts, and auth protection.', tags: ['React', 'TypeScript', 'Tailwind'], gradient: 'linear-gradient(135deg, #7C3AED, #5B21B6)', prompt: 'Generate a complete React dashboard template with sidebar navigation, stats cards, and dark theme using TypeScript and Tailwind CSS.' },
    { icon: FiDatabase, title: 'REST API with Auth', desc: 'Express.js API with JWT auth, middleware, and MongoDB connection.', tags: ['Node.js', 'Express', 'MongoDB'], gradient: 'linear-gradient(135deg, #06B6D4, #0891B2)', prompt: 'Generate a complete Node.js REST API with Express, JWT authentication, MongoDB with Mongoose, and CRUD endpoints.' },
    { icon: FiShield, title: 'Auth System', desc: 'Full authentication flow with login, register, refresh tokens, and guards.', tags: ['JWT', 'Bcrypt', 'Middleware'], gradient: 'linear-gradient(135deg, #10B981, #059669)', prompt: 'Build a complete authentication system with login, register, refresh tokens, password hashing with bcrypt, and protected route middleware.' },
    { icon: FiGlobe, title: 'Next.js Fullstack App', desc: 'Next.js 14 app with API routes, database, and deployment setup.', tags: ['Next.js', 'Prisma', 'PostgreSQL'], gradient: 'linear-gradient(135deg, #EC4899, #BE185D)', prompt: 'Create a complete Next.js 14 fullstack application with App Router, API routes, Prisma ORM, PostgreSQL database, and deployment configuration.' },
    { icon: FiCode, title: 'React Custom Hooks', desc: 'Collection of 10 essential custom hooks for real-world React apps.', tags: ['React', 'Hooks', 'TypeScript'], gradient: 'linear-gradient(135deg, #F59E0B, #D97706)', prompt: 'Generate 10 production-ready custom React hooks: useFetch, useLocalStorage, useDebounce, useIntersectionObserver, and more with TypeScript.' },
    { icon: FiZap, title: 'GraphQL API', desc: 'Apollo GraphQL server with resolvers, schemas, and authentication.', tags: ['GraphQL', 'Apollo', 'Node.js'], gradient: 'linear-gradient(135deg, #7C3AED, #06B6D4)', prompt: 'Build a complete GraphQL API with Apollo Server, type definitions, resolvers, mutations, subscriptions, and JWT authentication.' },
];

export default function TemplatesPage() {
    return (
        <div style={{ padding: '32px 36px', maxWidth: 1100, margin: '0 auto' }}>
            <div style={{ marginBottom: 40 }}>
                <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '5px 14px', background: 'rgba(6,182,212,0.1)', border: '1px solid rgba(6,182,212,0.2)', borderRadius: 100, fontSize: '0.72rem', fontWeight: 700, color: '#67E8F9', marginBottom: 14, letterSpacing: '0.05em', textTransform: 'uppercase' }}>
                    Templates
                </div>
                <h1 style={{ fontSize: '2rem', fontWeight: 900, letterSpacing: '-0.5px', color: '#fff', marginBottom: 8, fontFamily: 'var(--font-outfit)' }}>
                    Project Templates
                </h1>
                <p style={{ color: '#71717A', fontSize: '0.95rem' }}>
                    Production-ready templates generated by DevPilot AI. Click to start in chat.
                </p>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: 18 }}>
                {templates.map((t, i) => (
                    <motion.div key={t.title} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.07 }} whileHover={{ y: -4, transition: { duration: 0.2 } }}>
                        <Link href={`/chat?q=${encodeURIComponent(t.prompt)}`} style={{ textDecoration: 'none' }}>
                            <div style={{ background: '#111', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 20, padding: '26px', cursor: 'pointer', position: 'relative', overflow: 'hidden', transition: 'border-color 0.25s' }}
                                onMouseEnter={e => (e.currentTarget.style.borderColor = 'rgba(124,58,237,0.35)')}
                                onMouseLeave={e => (e.currentTarget.style.borderColor = 'rgba(255,255,255,0.06)')}>
                                <div style={{ position: 'absolute', top: -40, right: -40, width: 120, height: 120, background: t.gradient, borderRadius: '50%', filter: 'blur(50px)', opacity: 0.1, pointerEvents: 'none' }} />
                                <div style={{ width: 44, height: 44, borderRadius: 12, background: t.gradient, display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 16 }}>
                                    <t.icon size={20} color="#fff" />
                                </div>
                                <h3 style={{ fontSize: '0.98rem', fontWeight: 700, color: '#fff', marginBottom: 8 }}>{t.title}</h3>
                                <p style={{ fontSize: '0.85rem', color: '#71717A', lineHeight: 1.65, marginBottom: 16 }}>{t.desc}</p>
                                <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginBottom: 16 }}>
                                    {t.tags.map(tag => (
                                        <span key={tag} style={{ padding: '3px 9px', background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 100, fontSize: '0.7rem', color: '#71717A', fontWeight: 600 }}>{tag}</span>
                                    ))}
                                </div>
                                <div style={{ display: 'flex', alignItems: 'center', gap: 6, color: '#A78BFA', fontSize: '0.8rem', fontWeight: 600 }}>
                                    Generate in Chat <FiArrowRight size={13} />
                                </div>
                            </div>
                        </Link>
                    </motion.div>
                ))}
            </div>
        </div>
    );
}
